services:
  nginx:
    container_name: my-nginx    
    restart: always
    build:       
      context: ./stack-fe      
    ports:
      - 8001:80
    volumes:
      - ./nginx/config/default.conf:/etc/nginx/conf.d/default.conf    
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    container_name: my-db
    command: --init-file /data/application/init.sql
    volumes:
      - ./initDB.sql:/data/application/init.sql
    environment:
      - MYSQL_ROOT_PASSWORD=diennk@246
      - MYSQL_DATABASE=database_demo
    ports:
      - 3307:3306
  backend:
    depends_on:
      - mysqldb
    container_name: my-backend
    build: 
      context: ./stack-be
    environment:      
      - DATABASE_PORT=3307            
      - HOST=host.docker.internal
    ports:
      - 8000:8000
# docker compose -p hoidanit up -d