services:
  nginx:
    container_name: my-nginx    
    restart: always
    build:       
      context: ./stack-fe      
    ports:
      - 80:80
    volumes:
      - ./nginx/config/default.conf:/etc/nginx/conf.d/default.conf         
  mysqldb:
    platform: linux/x86_64
    image: mysql:5.7
    restart: unless-stopped
    container_name: my-db    
    command: --init-file /data/application/initDB.sql
    volumes:
      - my-datavolume:/var/lib/mysql
      - ./initDB.sql:/data/application/initDB.sql
    environment:
      - MYSQL_ROOT_PASSWORD=diennk@246
      - MYSQL_DATABASE=database_demo
    expose:
      - "3306"
  backend:
    depends_on:
      - mysqldb
    container_name: my-backend
    build: 
      context: ./stack-be
    environment:           
      - HOST=mysqldb
    links:
      - mysqldb
    expose:
      - "8000"
volumes:
  my-datavolume:
# docker compose -p hoidanit up -d